name: agriplant
description: Agriculture plant app
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  badges: ^3.1.1
  cloud_firestore: ^5.1.0
  dash_chat_2: ^0.0.21
  easy_stepper: ^0.7.3
  firebase_core: 3.2.0
  flutter:
    sdk: flutter
  flutter_gemini: ^2.0.4
  flutter_iconly: ^1.0.2
  google_fonts: ^5.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  permission_handler: ^11.3.1
  timelines: ^0.1.0

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/services/
    - shorebird.yaml
