name: agriplant
description: Agriculture plant app
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  badges: ^3.1.2
  camera: ^0.11.0+1
  chat_message_timestamp: ^0.0.1
  cloud_firestore: ^5.2.0
  dash_chat_2: ^0.0.21
  easy_stepper: ^0.8.5+1
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_chat_bubble: ^2.0.2
  flutter_gemini: ^2.0.4
  flutter_iconly: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  mobile_scanner: ^5.2.3
  permission_handler: ^11.3.1
  qr_flutter: ^4.1.0
  qr_scanner_overlay: ^0.0.2
  timelines: ^0.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "agrow"
  ios: "agrow"
  image_path: "assets/icon2.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/services/
    - assets/products/
    - assets/articles/
    - shorebird.yaml
