// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLdC3m4kAVfHYoXnWwWirhTesuGtoHRkg',
    appId: '1:110240005050:android:fec9f31f05a05e333c3b83',
    messagingSenderId: '110240005050',
    projectId: 'agrow-177c4',
    databaseURL: 'https://agrow-177c4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agrow-177c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_u8YTb_0g-1vXHKorKtob_5EJChki7cI',
    appId: '1:110240005050:ios:48a23bcae59cf4323c3b83',
    messagingSenderId: '110240005050',
    projectId: 'agrow-177c4',
    databaseURL: 'https://agrow-177c4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agrow-177c4.appspot.com',
    iosBundleId: 'com.example.agricplant.agriplant',
  );
}
